name: Build and Release

on:
  push:
    tags:
      - 'v*' # Тригер для створення релізу при пуші тегу (наприклад, v1.0)

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write # Необхідно для створення релізу та завантаження файлів

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022"

    - name: Build Project
      run: cmake --build build --config Release

    - name: Create Release Archive
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path MICFix_Release
        Copy-Item -Path "build\Release\MICFixService.dll" -Destination "MICFix_Release\"
        Copy-Item -Path "build\Release\MICFixInstall.exe" -Destination "MICFix_Release\"
        Copy-Item -Path "build\Release\MICFixUninstall.exe" -Destination "MICFix_Release\"
        Copy-Item -Path "README.md" -Destination "MICFix_Release\"
        Copy-Item -Path "README_UA.md" -Destination "MICFix_Release\"
        Copy-Item -Path "LICENSE" -Destination "MICFix_Release\"
        
        Compress-Archive -Path "MICFix_Release\*" -DestinationPath "MICFix_Release.zip"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: MICFix_Release.zip
        generate_release_notes: true
